version: '3'
services:
  tensorflow-notebook:
    image: jupyter/tensorflow-notebook
    build:
      context: ./notebook
      dockerfile: Dockerfile
    ports:
      - 8888:8888
  not-hot-dog:
    image: not-hot-dog
    build:
      context: ./notHotDogWeb
      dockerfile: Dockerfile
    ports:
      - 5000:5000