runtime: python3
env: flex
threadsafe: false
entrypoint: gunicorn -b :$PORT manage:app

resources:
  cpu: 2  # Number of cores. Default: 1
  memory_gb: 4.  # RAM in GB. Default: 0.6 GB

runtime_config:
    python_version: 3.5

# Define environment vars for app configuration.
env_variables:
  APPENGINE_CONFIG: 'production'
